### PR TITLE
Start stop

### LINKED ISSUE #26: When pressing "Q" to quit, PiWeatherRock restarts and pops back up in 10 seconds
Is there a way to quit PiWeatherRock by pressing "Q"? Right now, the programs pops back up 10 seconds after pressing "Q".  

But of course, `systemctl stop PiWeatherRock ` works well too from the terminal, so not a huge issue.

### PR DESCRIPTION
**Pull request by metaMMA**
- Add ability to start/stop application from config page.
- Fixes: https://github.com/genebean/PiWeatherRock/issues/26

NOTE: This PR is branched from `logging` PR. It's here for debugging purposes. I will create a new PR with these changes, once `logging` PR is merged.

### CODE REVIEW

**Comment by metaMMA** [comment]
Not sure if the refs to `MY_DISP` will cause any issues on lines 118 and 122

```
def get_windspeed_abbreviation(unit=MY_DISP.config["units"]):
    return get_abbreviation(units_decoder(unit)['windSpeed'])

def get_temperature_letter(unit=MY_DISP.config["units"]):
```

**Comment by metaMMA** [comment]
Not sure if the refs to `MY_DISP` will cause any issues on lines 118 and 122

```
def get_windspeed_abbreviation(unit=MY_DISP.config["units"]):
    return get_abbreviation(units_decoder(unit)['windSpeed'])

def get_temperature_letter(unit=MY_DISP.config["units"]):
```

**Comment by genebean** [comment]
You should be good to rebase now.

**Comment by genebean** [comment]
As part of this, what do you think of removing the restart always from the PiWeatherRock unit file?

**Comment by metaMMA** [comment]
> As part of this, what do you think of removing the restart always from the PiWeatherRock unit file?

I'm leaning toward leaving it in there. I think most exceptions are being caught, but in the case that something unforeseen does happen, maybe it's a good thing to automatically retry? 

I was thinking it might be a good idea to change to keybinding of `q` to mimic the way the `start/stop` slider works: change the lock file to `0`. What do you think?

**Pull request closed without merging**
